### PR TITLE
Integrate database

### PR DESCRIPTION
**Pull request by SScorp1on**
Added integration with PostgreSQL database

### CODE REVIEW

**Review by SScorp1on — COMMENTED** [review]
👍

**Review by Aspergillusplay — COMMENTED** [review]
Good job!

**Review by DmitryByrigin — COMMENTED** [review]
Great commit!

**Review by SScorp1on — COMMENTED** [review]
👍

**Review by Aspergillusplay — COMMENTED** [review]
+

**Review by Aspergillusplay — COMMENTED** [review]
+

**Review by Aspergillusplay — COMMENTED** [review]
+

**Comment by SScorp1on** [comment]
Just testing pull requests

**Pull request merged**
